# Generated by Django 2.1.5 on 2019-02-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190216_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.IntegerField(),
        ),
    ]
