# Generated by Django 2.1.5 on 2019-02-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190217_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='disaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Disaster'),
        ),
    ]
