# Generated by Django 2.1.5 on 2019-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190217_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
