# Generated by Django 2.1.5 on 2019-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190217_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
