# Generated by Django 2.1.5 on 2019-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190217_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
