# Generated by Django 2.1.5 on 2019-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumb_ups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
